# Generated by Django 5.2.1 on 2025-07-05 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_coach_alter_customuser_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('certifications', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo Coach',
                'verbose_name_plural': 'Profili Coach',
            },
        ),
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.OneToOneField(limit_choices_to={'role': 'standard'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignment', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assegnazione Cliente',
                'verbose_name_plural': 'Assegnazioni Clienti',
                'constraints': [models.UniqueConstraint(fields=('client',), name='unique_client_assignment')],
            },
        ),
    ]
