# Generated by Django 5.2.1 on 2025-07-05 15:52

from django.db import migrations

from django.db import models
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),

    ]
