# Generated by Django 5.2.1 on 2025-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_registration_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
