# Generated by Django 5.2.1 on 2025-07-06 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performance_rating', models.PositiveSmallIntegerField(blank=True, help_text='Valutazione da 1 a 10', null=True)),
            ],
            options={
                'verbose_name': 'Progresso Cliente',
                'verbose_name_plural': 'Progressi Clienti',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.AlterModelOptions(
            name='clientassignment',
            options={'ordering': ['-date_assigned'], 'verbose_name': 'Assegnazione Cliente', 'verbose_name_plural': 'Assegnazioni Clienti'},
        ),
        migrations.RemoveConstraint(
            model_name='clientassignment',
            name='unique_client_assignment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='coach',
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='date_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'standard'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_as_coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='clientassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client',), name='unique_active_client_assignment'),
        ),
        migrations.AddField(
            model_name='clientprogress',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='users.clientassignment'),
        ),
    ]
