# Generated by Django 5.2.1 on 2025-07-06 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clientprogress_alter_clientassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('action_url', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientassignment',
            options={'ordering': ['-date_requested'], 'verbose_name': 'Assegnazione Cliente', 'verbose_name_plural': 'Assegnazioni Clienti'},
        ),
        migrations.RemoveConstraint(
            model_name='clientassignment',
            name='unique_active_client_assignment',
        ),
        migrations.RenameField(
            model_name='clientassignment',
            old_name='date_assigned',
            new_name='date_requested',
        ),
        migrations.RemoveField(
            model_name='clientassignment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='date_responded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('accepted', 'Accettato'), ('rejected', 'Rifiutato'), ('ended', 'Terminato')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='clientassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('client',), name='unique_active_client_assignment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
