# Generated by Django 5.2.1 on 2025-07-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification_alter_clientassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='clientassignment',
            options={'ordering': ['-date_assigned'], 'verbose_name': 'Assegnazione Cliente', 'verbose_name_plural': 'Assegnazioni Clienti'},
        ),
        migrations.RemoveConstraint(
            model_name='clientassignment',
            name='unique_active_client_assignment',
        ),
        migrations.RenameField(
            model_name='clientassignment',
            old_name='date_requested',
            new_name='date_assigned',
        ),
        migrations.RemoveField(
            model_name='clientassignment',
            name='date_responded',
        ),
        migrations.RemoveField(
            model_name='clientassignment',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='clientassignment',
            name='status',
        ),
        migrations.AddField(
            model_name='clientassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='clientassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client',), name='unique_active_client_assignment'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
