# Generated by Django 5.2.1 on 2025-07-06 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Se privato, visibile solo al coach e non al cliente')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_comments', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.clientprogress')),
            ],
            options={
                'verbose_name': 'Commento Progresso',
                'verbose_name_plural': 'Commenti Progressi',
                'ordering': ['-created_at'],
            },
        ),
    ]
