# Generated by Django 5.2.1 on 2025-07-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_is_completed'),
        ('users', '0009_progresscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprogress',
            name='measurement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_report', to='goals.measurement'),
        ),
    ]
