# Generated by Django 5.2.1 on 2025-07-03 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-date'], 'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.AddField(
            model_name='goal',
            name='body_fat',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='goal',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='water_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
