# Generated by Django 5.2.1 on 2025-07-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-date'], 'verbose_name': 'Misurazione', 'verbose_name_plural': 'Misurazioni'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='body_fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Massa grassa (%)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Massa muscolare (kg)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='water_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Acqua corporea (%)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (kg)'),
        ),
    ]
