# Generated by Django 5.2.1 on 2025-07-02 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workout_options_remove_workout_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durata (min)'),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.TextField(default='Riscaldamento, Squat, Affondi', help_text='Separare gli esercizi con virgole', verbose_name='Esercizi svolti'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
