# Generated by Django 5.2.1 on 2025-07-02 23:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_workout_options_workout_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date'], 'verbose_name': 'Allenamento', 'verbose_name_plural': 'Allenamenti'},
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(verbose_name='Data allenamento'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Durata in minuti', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durata (min)'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Note aggiuntive'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
